version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    network_mode: "host"
    environment:
      - NEO4J_AUTH=neo4j/igris
    volumes:
      - ./neo4j_data:/data/
  igris:
    build: .
    container_name: igris
    network_mode: "host"
    volumes:
      - ./loot:/home/igris/loot
      - ./save:/home/igris/save
    depends_on:
      - neo4j
    restart: "no"
    entrypoint: [ "python3", "/home/igris/app/main.py" ]
    environment:
      - LOGURU_AUTOINIT=False
