version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    network_mode: "host"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/igris
  igris:
    build: .
    container_name: igris
    network_mode: "host"
    depends_on:
      - neo4j
    restart: "no"
    entrypoint: [ "python3", "/home/igris/app/main.py" ]
    environment:
      - LOGURU_AUTOINIT=False
